# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-06 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hc_pacientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeterminacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('order', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Determinacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('unitOfMeasure', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('order', models.IntegerField(null=True)),
                ('upperLimit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lowerLimit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_laboratory.CategoriaDeterminacion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DeterminacionValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('determinacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hc_laboratory.Determinacion')),
            ],
            options={
                'ordering': ['labResult', 'determinacion'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo'), (b'Error', b'Error')], default=b'Active', max_length=8)),
                ('createdOn', models.DateTimeField(auto_now=True)),
                ('modifiedOn', models.DateTimeField(null=True)),
                ('inputType', models.CharField(choices=[(b'Automatic', b'Manual'), (b'Manual', b'Automatico')], default=b'Manual', max_length=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hc_pacientes.Paciente')),
            ],
            options={
                'ordering': ['status', '-date'],
            },
        ),
        migrations.AddField(
            model_name='determinacionvalor',
            name='labResult',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='hc_laboratory.LabResult'),
        ),
    ]
