# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-23 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hc_laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
