# Generated by Django 2.2 on 2019-07-17 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_laboratory', '0002_labresult_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadeterminacion',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='determinacion',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hc_laboratory.CategoriaDeterminacion'),
        ),
        migrations.AlterField(
            model_name='determinacion',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='determinacionvalor',
            name='determinacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_laboratory.Determinacion'),
        ),
        migrations.AlterField(
            model_name='determinacionvalor',
            name='labResult',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='values', to='hc_laboratory.LabResult'),
        ),
        migrations.AlterField(
            model_name='determinacionvalor',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='inputType',
            field=models.CharField(choices=[('Automatic', 'Manual'), ('Manual', 'Automatico')], default='Manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo'), ('Error', 'Error')], default='Active', max_length=8),
        ),
    ]
