# Generated by Django 2.2 on 2020-02-04 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_laboratory', '0003_auto_20190717_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='determinacionvalor',
            name='labResult',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='hc_laboratory.LabResult'),
        ),
    ]
