# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-05 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hc_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='pns',
        ),
    ]
