# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-17 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_pacientes', '0002_remove_paciente_pns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='bornPlace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hc_common.Country'),
        ),
    ]
