# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hc_common', '0006_auto_20180906_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipalNumber', models.CharField(max_length=8)),
                ('licenseNumber', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=8, null=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('firstName', models.CharField(default=b'No informado', max_length=80)),
                ('otherNames', models.CharField(blank=True, max_length=80, null=True)),
                ('fatherSurname', models.CharField(default=b'No informado', max_length=80)),
                ('motherSurname', models.CharField(blank=True, max_length=40, null=True)),
                ('hceNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('documentNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[(b'Active', b'Activo'), (b'Inactive', b'Inactivo')], default=b'Active', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('primaryPhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('primaryPhoneContact', models.CharField(blank=True, max_length=40, null=True)),
                ('primaryPhoneMessage', models.NullBooleanField(default=False)),
                ('secondPhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('secondPhoneContact', models.CharField(blank=True, max_length=40, null=True)),
                ('secondPhoneMessage', models.NullBooleanField(default=False)),
                ('thirdPhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('thirdPhoneContact', models.CharField(blank=True, max_length=40, null=True)),
                ('thirdPhoneMessage', models.NullBooleanField(default=False)),
                ('documentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hc_common.DocumentType')),
                ('genderAtBirth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesionalGenderBirth', to='hc_common.SexType')),
                ('genderOfChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesionalGenderChoice', to='hc_common.SexType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
