# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-15 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hc_common', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hc_common.Persona')),
                ('municipalNumber', models.CharField(max_length=8)),
                ('licenseNumber', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=8, null=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('hc_common.persona',),
        ),
    ]
