# Generated by Django 2.2 on 2019-07-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_practicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='documentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hc_common.DocumentType'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='fatherSurname',
            field=models.CharField(default='No informado', max_length=80),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='firstName',
            field=models.CharField(default='No informado', max_length=80),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
    ]
