# Generated by Django 2.2 on 2020-01-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0010_protocol'),
        ('hc_practicas', '0003_auto_20190814_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesionalProtocol', to='hc_common.Protocol'),
        ),
    ]
