INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Antitoxina Tetánica+Vacuna anti-tetánica', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- cólera', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Difteria+Pertussis+Tétanos', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Difteria+Tétanos', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Fiebre amarilla ', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Influenza', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Influenza H1N1', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Haemophilus influenzae tipo b', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Haemophilus influenzae tipo b+Difteria+Pertussis+Tétanos', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Haemophilus influenzae tipo b+Difteria+Pertussis+Tétanos+Hep B', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Haemophilus influenzae tipo b+Difteria+Pertussis+Tétanos+Salk+Hep B', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Hepatitis A', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Hepatitis A+B', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Hepatitis B', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Meningococo Grupo C', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Neumococo 23 serotipos', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Neumococo 7 serotipos', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Papilomavirus', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Parotiditis+Rubíola+Sarampión ', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Poliomielitis Sabin', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Poliomielitis Salk', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Rabia', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Rotavirus', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Rubíola ', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Salmonella typhi', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Sarampión ', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Tetánica', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti- Varicela ', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna BCG', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Triple bacteriana', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna antigripal', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti-leptospira', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti-leptospira', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti-leptospira', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna triple bacteriana acelular', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('vacuna triple bacteriana acelular', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('vacuna anti-neumococo 13 serotipo', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('vacuna anti-neumococo 13 serotipo', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('vacuna anti-neumococo 13 serotipo', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('vacuna conjugada 13 serotipos', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('vacuna conjugada 13 serotipos', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('vacuna conjugada 13 serotipos', 'Active');
INSERT INTO "public"."hc_masters_vaccine" ("name", "status") VALUES('Vacuna anti neumococo 13 serotipos', 'Active')