# Generated by Django 2.2 on 2019-07-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalstudy',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicationType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hc_masters.MedicationType'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='medicationpresentation',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='presentations', to='hc_masters.Medication'),
        ),
        migrations.AlterField(
            model_name='medicationpresentation',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problemTypeTmp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hc_masters.ProblemType'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='state',
            field=models.CharField(choices=[('ToReview', 'ToReview'), ('Valid', 'Valid'), ('Invalid', 'Invalid')], default='ToReview', max_length=8),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
    ]
