insert into hc_common_protocol (id, name, description, status) values (1, '201637 SWORD', '201637 SWORD', 'Active');
insert into hc_common_protocol (id, name, description, status) values (2, 'AI438-047 - 205888', 'AI438-047 - 205888', 'Active');
insert into hc_common_protocol (id, name, description, status) values (3, '204861 Gemini', '204861 Gemini', 'Active');
insert into hc_common_protocol (id, name, description, status) values (4, 'GS-US-216-0128', 'GS-US-216-0128', 'Active');
insert into hc_common_protocol (id, name, description, status) values (5, 'ING117172 ARIA', 'ING117172 ARIA', 'Active');
insert into hc_common_protocol (id, name, description, status) values (6, 'MK-1439-018', 'MK-1439-018', 'Active');
insert into hc_common_protocol (id, name, description, status) values (7, 'MK-1439A-024', 'MK-1439A-024', 'Active');
insert into hc_common_protocol (id, name, description, status) values (8, '201585 ATLAS I', '201585 ATLAS I', 'Active');
insert into hc_common_protocol (id, name, description, status) values (9, '207966 ATLAS II', '207966 ATLAS II', 'Active');
insert into hc_common_protocol (id, name, description, status) values (10, 'TMC278-TIDP6-C222', 'TMC278-TIDP6-C222', 'Active');
insert into hc_common_protocol (id, name, description, status) values (11, 'HPTN083', 'HPTN083', 'Active');
insert into hc_common_protocol (id, name, description, status) values (12, '208090 SALSA', '208090 SALSA', 'Active');
insert into hc_common_protocol (id, name, description, status) values (13, 'FH-15 ANDES 2', 'FH-15 ANDES 2', 'Active');
insert into hc_common_protocol (id, name, description, status) values (14, 'FH-30', 'FH-30', 'Active');
insert into hc_common_protocol (id, name, description, status) values (15, 'FH-31', 'FH-31', 'Active');
insert into hc_common_protocol (id, name, description, status) values (16, 'FH-41', 'FH-41', 'Active');
insert into hc_common_protocol (id, name, description, status) values (17, 'FH-42 PADDLE 184-V', 'FH-42 PADDLE 184-V', 'Active');
insert into hc_common_protocol (id, name, description, status) values (18, 'FH-43 RESISTENCIA', 'FH-43 RESISTENCIA', 'Active');
insert into hc_common_protocol (id, name, description, status) values (19, 'HVTN MOSAICO', 'HVTN MOSAICO', 'Active');
insert into hc_common_protocol (id, name, description, status) values (20, 'MK8591A-020', 'MK8591A-020', 'Active');
insert into hc_common_protocol (id, name, description, status) values (21, 'Testeo', 'Testeo', 'Active');
insert into hc_common_protocol (id, name, description, status) values (22, 'ITS', 'ITS', 'Active');
insert into hc_common_protocol (id, name, description, status) values (23, 'Sin protocolo', 'Sin protocolo', 'Active');
insert into hc_common_protocol (id, name, description, status) values (24, 'Otros', 'Otros', 'Active');

SELECT setval('hc_common_protocol_id_seq', 24);