insert into hc_common_province (id, name, description, status) values (1, 'CIUDAD AUTÓNOMA DE BUENOS AIRES', 'CIUDAD AUTÓNOMA DE BUENOS AIRES', 'Active');
insert into hc_common_province (id, name, description, status) values (2, 'BUENOS AIRES', 'BUENOS AIRES', 'Active');
insert into hc_common_province (id, name, description, status) values (3, 'CATAMARCA', 'CATAMARCA', 'Active');
insert into hc_common_province (id, name, description, status) values (4, 'CORRIENTES', 'CORRIENTES', 'Active');
insert into hc_common_province (id, name, description, status) values (5, 'CHACO', 'CHACO', 'Active');
insert into hc_common_province (id, name, description, status) values (6, 'SAN LUIS', 'SAN LUIS', 'Active');
insert into hc_common_province (id, name, description, status) values (7, 'TIERRA DEL FUEGO', 'TIERRA DEL FUEGO', 'Active');
insert into hc_common_province (id, name, description, status) values (8, 'SALTA', 'SALTA', 'Active');
insert into hc_common_province (id, name, description, status) values (9, 'ENTRE RÍOS', 'ENTRE RÍOS', 'Active');
insert into hc_common_province (id, name, description, status) values (10, 'LA RIOJA', 'LA RIOJA', 'Active');
insert into hc_common_province (id, name, description, status) values (11, 'SANTIAGO DEL ESTERO', 'SANTIAGO DEL ESTERO', 'Active');
insert into hc_common_province (id, name, description, status) values (12, 'SAN JUAN', 'SAN JUAN', 'Active');
insert into hc_common_province (id, name, description, status) values (13, 'LA PAMPA', 'LA PAMPA', 'Active');
insert into hc_common_province (id, name, description, status) values (14, 'MENDOZA', 'MENDOZA', 'Active');
insert into hc_common_province (id, name, description, status) values (15, 'MISIONES', 'MISIONES', 'Active');
insert into hc_common_province (id, name, description, status) values (16, 'FORMOSA', 'FORMOSA', 'Active');
insert into hc_common_province (id, name, description, status) values (17, 'NEUQUÉN', 'NEUQUÉN', 'Active');
insert into hc_common_province (id, name, description, status) values (18, 'RÍO NEGRO', 'RÍO NEGRO', 'Active');
insert into hc_common_province (id, name, description, status) values (19, 'SANTA FÉ', 'SANTA FÉ', 'Active');
insert into hc_common_province (id, name, description, status) values (20, 'TUCUMÁN', 'TUCUMÁN', 'Active');
insert into hc_common_province (id, name, description, status) values (21, 'CHUBUT', 'CHUBUT', 'Active');
insert into hc_common_province (id, name, description, status) values (22, 'CÓRDOBA', 'CÓRDOBA', 'Active');
insert into hc_common_province (id, name, description, status) values (23, 'JUJUY', 'JUJUY', 'Active');
insert into hc_common_province (id, name, description, status) values (24, 'SANTA CRUZ', 'SANTA CRUZ', 'Active');
SELECT setval('hc_common_province_id_seq', 24);
