insert into hc_common_socialservice (id, name, description, status) values (1, 'UP', 'UP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (2, 'ACTORES', 'ACTORES', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (3, 'ALTA SALUD', 'ALTA SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (4, 'AMG', 'AMG', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (5, 'AMSCA', 'AMSCA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (6, 'ANDAR', 'ANDAR', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (7, 'APRES', 'APRES', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (8, 'APS', 'APS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (9, 'ASOC.ESC. SAN PEDRO', 'ASOC.ESC. SAN PEDRO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (10, 'BANCARIO', 'BANCARIO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (11, 'BCO.PROV', 'BCO.PROV', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (12, 'BOREAL', 'BOREAL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (13, 'C. DE STA CRUZ', 'C. DE STA CRUZ', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (14, 'C. SERV.S.T', 'C. SERV.S.T', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (15, 'C.S.S.J.C', 'C.S.S.J.C', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (16, 'C.SERV.STC', 'C.SERV.STC', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (17, 'CAJA FORENSE', 'CAJA FORENSE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (18, 'CAJA SERV', 'CAJA SERV', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (19, 'CAJA SERV. SOCIAL', 'CAJA SERV. SOCIAL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (20, 'CAJA SS', 'CAJA SS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (21, 'CASA', 'CASA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (22, 'CEFRAN', 'CEFRAN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (23, 'CIPA', 'CIPA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (24, 'CIRME', 'CIRME', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (25, 'CM SALUD', 'CM SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (26, 'COBERMED', 'COBERMED', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (27, 'COLEGIO DE ESCRIBANOS DE LA PCIA DE BS AS', 'COLEGIO DE ESCRIBANOS DE LA PCIA DE BS AS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (28, 'CONSTRUIR', 'CONSTRUIR', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (29, 'CORPOMEDICIN', 'CORPOMEDICIN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (30, 'CRUZ ROJA', 'CRUZ ROJA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (31, 'DAS', 'DAS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (32, 'DASUTEN', 'DASUTEN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (33, 'DASMI', 'DASMI', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (34, 'DIBA', 'DIBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (35, 'DIBPFA', 'DIBPFA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (36, 'DOCTHOS', 'DOCTHOS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (37, 'DOSUBA', 'DOSUBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (38, 'ESCRIBANOS', 'ESCRIBANOS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (39, 'FUNDACION HUESPED', 'FUNDACION HUESPED', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (40, 'FATSA', 'FATSA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (41, 'FEMEDICA', 'FEMEDICA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (42, 'GALENO', 'GALENO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (43, 'GASTRONOMICOS', 'GASTRONOMICOS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (44, 'H. BRITANICO', 'H. BRITANICO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (45, 'H. ITALIANO', 'H. ITALIANO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (46, 'IAPOS', 'IAPOS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (47, 'IMOS', 'IMOS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (48, 'INT, MEDICA', 'INT, MEDICA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (49, 'IOMA', 'IOMA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (50, 'IOSPER', 'IOSPER', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (51, 'IPS', 'IPS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (52, 'ISSNQN', 'ISSNQN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (53, 'KOS (MEDICUS)', 'KOS (MEDICUS)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (54, 'LA CAJA', 'LA CAJA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (55, 'MAGNA SALUD', 'MAGNA SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (56, 'MAQUINISTAS NAVALES', 'MAQUINISTAS NAVALES', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (57, 'MASSALIN', 'MASSALIN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (58, 'MED', 'MED', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (59, 'MEDICALS', 'MEDICALS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (60, 'MEDICOS', 'MEDICOS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (61, 'MEDICUS', 'MEDICUS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (62, 'MEDIFE', 'MEDIFE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (63, 'MEDIN', 'MEDIN', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (64, 'MGN Salud', 'MGN Salud', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (65, 'OMINT', 'OMINT', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (66, 'OPESSA', 'OPESSA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (67, 'OPTAR', 'OPTAR', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (68, 'OSA (SMG)', 'OSA (SMG)', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (69, 'OSADEF', 'OSADEF', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (70, 'OSBA', 'OSBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (71, 'OSCHOCA', 'OSCHOCA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (72, 'OSDE', 'OSDE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (73, 'OSDEP', 'OSDEP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (74, 'OSDEPYM', 'OSDEPYM', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (75, 'OSDIPP', 'OSDIPP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (76, 'OSDOP', 'OSDOP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (77, 'OSECAC', 'OSECAC', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (78, 'OSEMM', 'OSEMM', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (79, 'OSEP', 'OSEP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (80, 'OSFA', 'OSFA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (81, 'OSIM', 'OSIM', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (82, 'OSIPA ', 'OSIPA ', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (83, 'OSMA', 'OSMA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (84, 'OSMATA', 'OSMATA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (85, 'OSMECOM', 'OSMECOM', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (86, 'OSMECON', 'OSMECON', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (87, 'OSMISS', 'OSMISS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (88, 'OSOCNA', 'OSOCNA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (89, 'OSPAC', 'OSPAC', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (90, 'OSPACTA', 'OSPACTA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (91, 'OSPADEP', 'OSPADEP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (92, 'OSPAT', 'OSPAT', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (93, 'OSPE', 'OSPE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (94, 'OSPECA', 'OSPECA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (95, 'OSPECOM', 'OSPECOM', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (96, 'OSPECYRA', 'OSPECYRA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (97, 'OSPEDYC', 'OSPEDYC', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (98, 'OSPEGAP', 'OSPEGAP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (99, 'OSPEP - Panaderos', 'OSPEP - Panaderos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (100, 'OSPERYH', 'OSPERYH', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (101, 'OSPESGYPE', 'OSPESGYPE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (102, 'OSPIA', 'OSPIA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (103, 'OSPIC', 'OSPIC', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (104, 'OSPIL', 'OSPIL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (105, 'OSPIP', 'OSPIP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (106, 'OSPIQYP', 'OSPIQYP', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (107, 'OSPIT', 'OSPIT', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (108, 'OSPLAD', 'OSPLAD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (109, 'OSPM', 'OSPM', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (110, 'OSPOCE', 'OSPOCE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (111, 'OSPRERA', 'OSPRERA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (112, 'OSPTV', 'OSPTV', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (113, 'OSTEL', 'OSTEL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (114, 'OSUTHGRA', 'OSUTHGRA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (115, 'P. JUDICIAL', 'P. JUDICIAL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (116, 'PAMI', 'PAMI', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (117, 'PRIVADO', 'PRIVADO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (118, 'PASTELEROS', 'PASTELEROS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (119, 'PASTEUR', 'PASTEUR', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (120, 'PODER JUDICIAL', 'PODER JUDICIAL', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (121, 'PRENSA', 'PRENSA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (122, 'PRENSA MED', 'PRENSA MED', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (123, 'PROFE', 'PROFE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (124, 'PROG. MEDICOS', 'PROG. MEDICOS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (125, 'PROTEXIA', 'PROTEXIA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (126, 'RED ARG DE SALUD', 'RED ARG DE SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (127, 'SADAIC', 'SADAIC', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (128, 'SAMA', 'SAMA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (129, 'SAMED', 'SAMED', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (130, 'SEGUROS', 'SEGUROS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (131, 'SEROS', 'SEROS', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (132, 'SICGBA', 'SICGBA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (133, 'SMG', 'SMG', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (134, 'SMG OSPOCE', 'SMG OSPOCE', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (135, 'TIM', 'TIM', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (136, 'TV SALUD', 'TV SALUD', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (137, 'UOCRA', 'UOCRA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (138, 'SIMECO', 'SIMECO', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (139, 'OSPEP - Espectaculos Publicos', 'OSPEP - Espectaculos Publicos', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (140, 'CIBIC', 'CIBIC', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (141, 'OSPEP - SYGMA', 'OSPEP - SYGMA', 'Active');
insert into hc_common_socialservice (id, name, description, status) values (142, 'OSCOEMA - RM RESPUESTAMEDICA', 'OSCOEMA - RM RESPUESTAMEDICA', 'Active');
SELECT setval('hc_common_socialservice_id_seq', 142);
