# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-17 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0006_auto_20180906_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialservice',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='socialservice',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
