# Generated by Django 2.2 on 2020-01-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_common', '0009_auto_20190717_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
