# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-17 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hc_hce', '0002_auto_20181205_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientarvtreatmentmedication',
            name='profesional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
