# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-05 18:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0004_auto_20190403_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvaccine',
            options={'ordering': ['state', '-appliedDate']},
        ),
        migrations.AddField(
            model_name='patientproblem',
            name='aditionalData',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
