# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-03 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0003_patientarvtreatmentmedication_profesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvaccine',
            options={'ordering': ['state', '-appliedDate']},
        ),
        migrations.AlterField(
            model_name='patientarvprescriptionmedication',
            name='quantityPerDay',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientarvprescriptionmedication',
            name='quantityPerMonth',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientarvtreatmentmedication',
            name='quantityPerDay',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientarvtreatmentmedication',
            name='quantityPerMonth',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='quantityPerDay',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='quantityPerMonth',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
