# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-05 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0003_patientarvtreatmentmedication_profesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvaccine',
            options={'ordering': ['state', '-appliedDate']},
        ),
    ]
