# Generated by Django 2.2 on 2019-07-17 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0004_auto_20190405_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientarvprescription',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientarvprescription',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='patientarvprescription',
            name='prescripctionType',
            field=models.CharField(choices=[('Vaccine', 'Vaccine'), ('Arv', 'Arv'), ('Prophylaxis', 'Prophylaxis'), ('General', 'General')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientarvprescriptionmedication',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hc_masters.Medication'),
        ),
        migrations.AlterField(
            model_name='patientarvprescriptionmedication',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptedMedications', to='hc_hce.PatientARVPrescription'),
        ),
        migrations.AlterField(
            model_name='patientarvtreatment',
            name='changeReason',
            field=models.CharField(choices=[('Toxicidad', 'Toxicidad'), ('Abandono', 'Abandono'), ('Simplificacion', 'Simplificacion'), ('Fallo', 'Fallo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientarvtreatment',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='patientarvtreatment',
            name='patientProblem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hc_hce.PatientProblem'),
        ),
        migrations.AlterField(
            model_name='patientarvtreatment',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientarvtreatment',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Error', 'Error')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='patientarvtreatmentmedication',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hc_masters.Medication'),
        ),
        migrations.AlterField(
            model_name='patientarvtreatmentmedication',
            name='patientARVTreatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientARVTreatmentMedications', to='hc_hce.PatientARVTreatment'),
        ),
        migrations.AlterField(
            model_name='patientarvtreatmentmedication',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientarvtreatmentmedication',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Error', 'Error')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='patientclinicalstudyresult',
            name='clinicalStudy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_masters.ClinicalStudy'),
        ),
        migrations.AlterField(
            model_name='patientclinicalstudyresult',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='patientclinicalstudyresult',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientclinicalstudyresult',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Error', 'Error')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='patientfamilyhistoryproblem',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='patientfamilyhistoryproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hc_masters.Problem'),
        ),
        migrations.AlterField(
            model_name='patientfamilyhistoryproblem',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientfamilyhistoryproblem',
            name='relationship',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Brother', 'Brother'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('Other', 'Other')], default='Other', max_length=15),
        ),
        migrations.AlterField(
            model_name='patientfamilyhistoryproblem',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Error', 'Error')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hc_masters.Medication'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='medicationPresentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hc_masters.MedicationPresentation'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='patientProblem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hc_hce.PatientProblem'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Error', 'Error')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='patientprescription',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprescription',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='patientprescription',
            name='prescripctionType',
            field=models.CharField(choices=[('Vaccine', 'Vaccine'), ('Arv', 'Arv'), ('Prophylaxis', 'Prophylaxis'), ('General', 'General')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprescriptionmedication',
            name='patientMedication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hc_hce.PatientMedication'),
        ),
        migrations.AlterField(
            model_name='patientprescriptionmedication',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptedMedications', to='hc_hce.PatientPrescription'),
        ),
        migrations.AlterField(
            model_name='patientprescriptionmedication',
            name='quantityPerDay',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientprescriptionmedication',
            name='quantityPerMonth',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientproblem',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='patientproblem',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientproblem',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Error', 'Error')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='patientvaccine',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='patientvaccine',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientvaccine',
            name='state',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Error', 'Error')], default='Applied', max_length=8),
        ),
        migrations.AlterField(
            model_name='patientvaccineprescription',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientvaccineprescription',
            name='paciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='patientvaccineprescription',
            name='prescripctionType',
            field=models.CharField(choices=[('Vaccine', 'Vaccine'), ('Arv', 'Arv'), ('Prophylaxis', 'Prophylaxis'), ('General', 'General')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hc_pacientes.Paciente'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='state',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Canceled', 'Canceled')], default='Open', max_length=8),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='visitevent',
            name='status',
            field=models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='visitevent',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='hc_hce.Visit'),
        ),
    ]
