# Generated by Django 2.2 on 2019-09-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0005_auto_20190717_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvaccine',
            name='appliedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
