# Generated by Django 2.2 on 2019-09-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0006_auto_20190910_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvaccine',
            name='appliedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
