# Generated by Django 2.2 on 2019-11-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0008_importation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importation',
            old_name='createdOn',
            new_name='creado',
        ),
    ]
