# Generated by Django 2.2 on 2019-11-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0009_auto_20191128_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importation',
            old_name='creado',
            new_name='created',
        ),
    ]
