# Generated by Django 2.2 on 2019-11-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0011_auto_20191128_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportationDeterminationRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('determination_id', models.IntegerField(blank=True, default=0, null=True)),
                ('determination_version_id', models.IntegerField(blank=True, default=0, null=True)),
                ('determination_description', models.CharField(blank=True, max_length=150, null=True)),
                ('determination_code', models.CharField(blank=True, max_length=10, null=True)),
                ('determination_number', models.IntegerField(blank=True, default=0, null=True)),
                ('processed_determination_id', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ImportationLabRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_Date', models.DateField(blank=True, null=True)),
                ('lab_id', models.IntegerField(blank=True, default=0, null=True)),
                ('processed_lab_id', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ImportationPatientRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(blank=True, default=0, null=True)),
                ('surname', models.CharField(blank=True, max_length=60, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('documentType', models.CharField(blank=True, max_length=5, null=True)),
                ('documentNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('processed_patient_id', models.IntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
