# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0014_auto_20191226_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ImportationRegister',
            name='determination_number',
            field=models.CharField(max_length=150, null=True)
        ),
        migrations.AlterField(
            model_name='ImportationDeterminationRelationship',
            name='determination_number',
            field=models.CharField(max_length=150, null=True)
        ),
    ]
