# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_hce', '0015_auto_20191226_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ImportationLabRelationship',
            name='paciente_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
